name: neom_generator
description: Neom Generator for Open Neom.
version: 2.0.0
homepage: https://github.com/Open-Neom/neom_generator

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core: ^2.0.0
  neom_commons: ^2.0.0
  neom_sound: ^1.0.0
  neom_states: ^1.0.0
  neom_vr: ^1.2.0

  sleek_circular_slider: ^2.1.0
  fl_chart: ^0.70.2
  pitch_detector_dart: ^0.0.7

  #Tonic is a Flutter-compatible Dart package that models components of music theory.
  #Used for Neom Harmony
  #tonic: ^0.2.4

  # TRANSITIVE DEPENDENCIES FOR PUB.DEV PUBLISHING
  cloud_firestore: ^6.2.0
  sint: ^1.3.0
  enum_to_string: ^2.2.1
  rflutter_alert: ^2.0.7
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.0
  webview_flutter_platform_interface: ^2.14.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.12.0
  path_provider: ^2.1.5
  flutter_sound: ^9.30.0
  logger: ^2.7.0
  web: ^1.1.0
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  shaders:
    - shaders/mandelbrot.frag
    - shaders/julia.frag
    - shaders/burning_ship.frag
    - shaders/newton.frag
    - shaders/multibrot.frag
